### ISSUE TITLE
Add link back to this repository in package.json/NPM

### ISSUE THREAD

**Issue by esjewett** [ui5-community/ui5-cc-md#3]
Currently in NPM there is no link back to this repo to indicate that it is the source for this library.

https://www.npmjs.com/package/ui5-cc-md

vs. 

https://www.npmjs.com/package/@openui5/sap.ui.core (which has a repository link)

**Comment by wridgeu** [comment]
Hey @esjewett, I added the respective link to the package.json, had that on my mind too! Thanks for letting us know, I think @vobu  will republish it after deciding on the license with @petermuessig regarding #2 .

Thanks!
